### ISSUE TITLE
Python 3.5.1 AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by gtors** [seomoz/url-py#37] opened 2016-03-18 08:47 UTC
This code cause exception:
```
import url
url.parse('http://example.com')
```

**Comment by b4hand** [comment] 2016-03-18 15:57
It would be a lot more helpful if you gave the full stack trace in an error report.

I can reproduce this:
```
$ python
Python 3.5.1 (default, Mar 18 2016, 08:38:49)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import url
>>> url.parse('http://example.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brandon/.pyenv/versions/3.5.1/lib/python3.5/site-packages/url.py", line 54, in parse
    return URL.parse(url, encoding)
  File "/Users/brandon/.pyenv/versions/3.5.1/lib/python3.5/site-packages/url.py", line 85, in parse
    url.decode(encoding).encode('utf-8'))
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by b4hand** [comment] 2016-03-18 16:00
FWIW, this is a general incompatibility with Python 3, rather than something specific to Python 3.5.1. Currently this package does not support Python 3, but we would accept a pull request that provided such compatibility.

**Comment by b4hand** [comment] 2016-03-18 16:01
Closing as a duplicate of #3.

**Closed by b4hand** 2016-03-18 16:01 UTC
